# site_name: 理论知识库

# theme:
#   name: 'rtd-dropdown'
#   extra_css:
#     - styles/custom.css
#   features:
#     - navigation.top        # 顶部固定导航栏
#     - navigation.expand     # 自动展开当前目录
#     - navigation.path       # 显示页面路径

# markdown_extensions:
#   - pymdownx.arithmatex:
#       generic: true
#   - admonition #便利贴
#   - pymdownx.details #块折叠
#   - pymdownx.superfences #块嵌套

# # extra_javascript:
# #   - javascripts/mathjax.js
# #   - https://polyfill.io/v3/polyfill.min.js?features=es6
# #   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# extra_javascript:
#   - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.8/katex.min.js
#   - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.8/contrib/auto-render.min.js # 添加自动渲染
#   - javascripts/katex.js


# extra_css:
#   - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.8/katex.min.css # KaTeX CSS

site_name: 理论知识库
theme:
  name: 'rtd-dropdown'
  extra_css:
    - styles/custom.css
  features:
    - navigation.top
    - navigation.expand
    - navigation.path
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
extra_javascript:
  # ========== 数学公式支持 ==========
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.8/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.8/contrib/auto-render.min.js
  - javascripts/katex-init.js  # KaTeX初始化

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.8/katex.min.css